services:
  # mongo:
  #   image: mongo:latest
  #   container_name: mongo_db
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db

  worker-sensores:
    build: .
    container_name: mqtt_worker
    env_file:
      - prod.env
    environment:
      - WORKER_MODE=sensors
      - MONGO_COLLECTION=dados
      - MQTT_TOPIC=esp8266/sensors
    restart: always

  worker-logs:
    build: .
    container_name: mqtt_logs
    env_file:
      - prod.env
    environment:
      - WORKER_MODE=logs
      - MONGO_COLLECTION=logs
      - MQTT_TOPIC=esp8266/logs
    restart: always

volumes:
  mongo_data:
